### ISSUE TITLE
Additional motion bindings

### ISSUE THREAD

**Issue by Iron-E** [Iron-E/nvim-tabmode#4]
It has been suggested by @galou that there be additional bindings for navigating tabs. As such I will add more so that people don't have to guess how to use this plugin.

**Comment by Iron-E** [comment]
Is there anything else you would like me to add while I have the PR open?

**Comment by galou** [comment]
I guess that the question is for me. There is nothing I can think of right now. Thanks!

**Comment by Iron-E** [comment]
Great! I'll merge it in.
